import KNConjectures.Projection

set_option linter.unusedSectionVars false

/-!
# Pair-source projection and overlap

This file gives the set-source version of the cluster projection and the overlap lemma used in
the repaired fixed-minimizer argument.  The source is the two-point set `{v, w'}`.
-/

noncomputable section

namespace KNAll

open MeasureTheory Set Percolation.Literature.LatticeModels Percolation.Literature
open Percolation.Continuity
open scoped Classical

variable {V : Type*} [Fintype V]

/-- The union of the two open vertex clusters generated by a pair of vertices. -/
def pairCluster (ω : BondConfig V) (v w' : V) : Set V :=
  openCluster ω v ∪ openCluster ω w'

/-- The event that neither vertex of the pair source is joined to `a`. -/
def pairAvoid (v w' a : V) : Set (BondConfig V) :=
  {ω | ¬ (openGraph ω).Reachable v a ∧ ¬ (openGraph ω).Reachable w' a}

/-- The event that at least one vertex of the pair source is joined to a vertex of `T`. -/
def pairConn (v w' : V) (T : Finset V) : Set (BondConfig V) :=
  {ω | ∃ t ∈ T, (openGraph ω).Reachable v t ∨ (openGraph ω).Reachable w' t}

/-- The vertex carrier of the explored set-cluster of `{v,w'}` is the union of the two vertex
clusters. -/
theorem pairCluster_eq_setCl_span (ω : BondConfig V) (v w' : V) :
    pairCluster ω v w' =
      {x | x = v ∨ x = w' ∨ ∃ e ∈ BHK2006.setCl ω ({v, w'} : Set V), x ∈ e} := by
  ext x
  simp only [pairCluster, mem_union, KNPreFKG.openCluster_eq_setOf_openEdgeCluster,
    mem_setOf_eq, BHK2006.mem_setCl_iff, mem_insert_iff, mem_singleton_iff]
  constructor
  · rintro (hv | hw)
    · rcases hv with rfl | ⟨e, he, hxe⟩
      · exact Or.inl rfl
      · exact Or.inr (Or.inr ⟨e, ⟨v, Or.inl rfl, he⟩, hxe⟩)
    · rcases hw with rfl | ⟨e, he, hxe⟩
      · exact Or.inr (Or.inl rfl)
      · exact Or.inr (Or.inr ⟨e, ⟨w', Or.inr rfl, he⟩, hxe⟩)
  · rintro (rfl | rfl | ⟨e, ⟨s, hs, he⟩, hxe⟩)
    · exact Or.inl (Or.inl rfl)
    · exact Or.inr (Or.inl rfl)
    · rcases hs with rfl | rfl
      · exact Or.inl (Or.inr ⟨e, he, hxe⟩)
      · exact Or.inr (Or.inr ⟨e, he, hxe⟩)

/-- The deleted-pair set associated with the explored set-cluster of `{v,w'}` is `bar` of the
pair-cluster union. -/
theorem barOf_pair_eq_bar (ω : BondConfig V) (v w' : V) :
    BHK2006.barOf ({v, w'} : Set V) (BHK2006.setCl ω ({v, w'} : Set V)) =
      bar (pairCluster ω v w') := by
  rw [BHK2006.barOf_setCl_eq]
  ext e
  simp only [bar, pairCluster, mem_setOf_eq, mem_union, openCluster]
  constructor
  · rintro ⟨x, hxe, s, hs, hsx⟩
    rcases hs with rfl | rfl
    · exact ⟨x, hxe, Or.inl hsx⟩
    · exact ⟨x, hxe, Or.inr hsx⟩
  · rintro ⟨x, hxe, hx | hx⟩
    · exact ⟨x, hxe, v, Or.inl rfl, hx⟩
    · exact ⟨x, hxe, w', Or.inr rfl, hx⟩

/-- Tower property after exploring the set-cluster generated by `{v,w'}`.  It is stated for an
arbitrary event determined by that complete explored edge set. -/
theorem tower_pairCluster (w : Sym2 V → unitInterval) (v w' a : V) (F : Set V → ℝ)
    (𝒮 : Set (Set (Sym2 V))) :
    ∫ ω in pairAvoid v w' a ∩
          {ω | BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮},
        F (openCluster ω a) ∂(prodBernoulli w) =
      ∫ ω in pairAvoid v w' a ∩
          {ω | BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮},
        (∫ η, F (openCluster (η \ bar (pairCluster ω v w')) a) ∂(prodBernoulli w))
          ∂(prodBernoulli w) := by
  classical
  set μ := prodBernoulli w with hμ
  set D : Set (BondConfig V) := pairAvoid v w' a with hD
  have hDiff : ∀ ω : BondConfig V, ω ∈ D ↔
      ∀ s ∈ ({v, w'} : Set V), ∀ t ∈ ({a} : Set V),
        ¬ (openGraph ω).Reachable s t := by
    intro ω
    simp only [hD, pairAvoid, mem_setOf_eq, mem_insert_iff, mem_singleton_iff, forall_eq]
    constructor
    · rintro ⟨hv, hw⟩ s (rfl | rfl)
      · exact hv
      · exact hw
    · intro h
      exact ⟨h v (Or.inl rfl), h w' (Or.inr rfl)⟩
  have hm : ∑ ω : Set (Sym2 V), BHK2006.weight (fun e => (w e : ℝ)) ω = 1 := by
    have h1 := BHK2006.integral_prodBernoulli_eq_sum w fun _ => (1 : ℝ)
    simp only [integral_const, probReal_univ, smul_eq_mul, mul_one] at h1
    exact h1.symm
  have key := BHK2006.set_sum_cond_cluster (fun e => (w e : ℝ)) hm
    ({v, w'} : Set V) ({a} : Set V)
    (fun K L => Percolation.Literature.DecisionTree.ind 𝒮 K *
      F {z | z = a ∨ ∃ e ∈ L, z ∈ e}) hDiff
  simp only [BHK2006.setCl_singleton] at key
  have hvert : ∀ η : BondConfig V,
      F {z | z = a ∨ ∃ e ∈ openEdgeCluster η a, z ∈ e} = F (openCluster η a) :=
    fun η => KNPreFKG.clusterFun_openEdgeCluster F η a
  simp only [hvert] at key
  rw [← integral_indicator (MeasurableSet.of_discrete),
    ← integral_indicator (MeasurableSet.of_discrete),
    BHK2006.integral_prodBernoulli_eq_sum, BHK2006.integral_prodBernoulli_eq_sum]
  have hL : ∀ ω : BondConfig V,
      (D ∩ {ω | BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮}).indicator
          (fun ω => F (openCluster ω a)) ω =
        Percolation.Literature.DecisionTree.ind 𝒮
            (BHK2006.setCl ω ({v, w'} : Set V)) *
          F (openCluster ω a) * Percolation.Literature.DecisionTree.ind D ω := by
    intro ω
    by_cases h1 : ω ∈ D
    · by_cases h2 : BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮
      · rw [indicator_of_mem (show ω ∈ D ∩
            {ω | BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮} from ⟨h1, h2⟩),
          Percolation.Literature.DecisionTree.ind_of_mem h1,
          Percolation.Literature.DecisionTree.ind_of_mem h2]
        ring
      · rw [indicator_of_notMem (fun h => h2 h.2),
          Percolation.Literature.DecisionTree.ind_of_not_mem h2]
        ring
    · rw [indicator_of_notMem (fun h => h1 h.1),
        Percolation.Literature.DecisionTree.ind_of_not_mem h1]
      ring
  have hR : ∀ ω : BondConfig V,
      (D ∩ {ω | BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮}).indicator
          (fun ω => ∫ η,
            F (openCluster (η \ BHK2006.barOf ({v, w'} : Set V)
              (BHK2006.setCl ω ({v, w'} : Set V))) a) ∂μ) ω =
        (∑ η : Set (Sym2 V), BHK2006.weight (fun e => (w e : ℝ)) η *
          (Percolation.Literature.DecisionTree.ind 𝒮
              (BHK2006.setCl ω ({v, w'} : Set V)) *
            F (openCluster (η \ BHK2006.barOf ({v, w'} : Set V)
              (BHK2006.setCl ω ({v, w'} : Set V))) a))) *
          Percolation.Literature.DecisionTree.ind D ω := by
    intro ω
    have hint : (∫ η,
          F (openCluster (η \ BHK2006.barOf ({v, w'} : Set V)
            (BHK2006.setCl ω ({v, w'} : Set V))) a) ∂μ) =
        ∑ η : Set (Sym2 V), BHK2006.weight (fun e => (w e : ℝ)) η *
          F (openCluster (η \ BHK2006.barOf ({v, w'} : Set V)
            (BHK2006.setCl ω ({v, w'} : Set V))) a) :=
      BHK2006.integral_prodBernoulli_eq_sum w _
    by_cases h1 : ω ∈ D
    · by_cases h2 : BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮
      · rw [indicator_of_mem (show ω ∈ D ∩
            {ω | BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮} from ⟨h1, h2⟩),
          Percolation.Literature.DecisionTree.ind_of_mem h1,
          Percolation.Literature.DecisionTree.ind_of_mem h2, hint]
        simp only [one_mul, mul_one]
      · rw [indicator_of_notMem (fun h => h2 h.2),
          Percolation.Literature.DecisionTree.ind_of_not_mem h2]
        simp only [zero_mul, mul_zero, Finset.sum_const_zero]
    · rw [indicator_of_notMem (fun h => h1 h.1),
        Percolation.Literature.DecisionTree.ind_of_not_mem h1]
      ring
  simp_rw [← barOf_pair_eq_bar]
  simp only [hL, hR]
  exact key

/-- Pair-source projection identity for every event determined by its explored set-cluster. -/
theorem setIntegral_sub_eq_projFunA_pair_setCl (w : Sym2 V → unitInterval) (v w' a : V)
    (F : Set V → ℝ) (𝒮 : Set (Set (Sym2 V))) :
    ∫ ω in pairAvoid v w' a ∩
          {ω | BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮},
        (F (pairCluster ω v w') - F (openCluster ω a)) ∂(prodBernoulli w) =
      ∫ ω in pairAvoid v w' a ∩
          {ω | BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮},
        projFunA w a F (pairCluster ω v w') ∂(prodBernoulli w) := by
  simp only [projFunA]
  rw [integral_sub (Integrable.of_finite).integrableOn (Integrable.of_finite).integrableOn,
    integral_sub (Integrable.of_finite).integrableOn (Integrable.of_finite).integrableOn,
    tower_pairCluster]

/-- Pair-source projection identity on the whole pair-avoidance event. -/
theorem setIntegral_sub_eq_projFunA_pair (w : Sym2 V → unitInterval) (v w' a : V)
    (F : Set V → ℝ) :
    ∫ ω in pairAvoid v w' a,
        (F (pairCluster ω v w') - F (openCluster ω a)) ∂(prodBernoulli w) =
      ∫ ω in pairAvoid v w' a,
        projFunA w a F (pairCluster ω v w') ∂(prodBernoulli w) := by
  simpa only [mem_univ, setOf_true, inter_univ] using
    (setIntegral_sub_eq_projFunA_pair_setCl w v w' a F
      (Set.univ : Set (Set (Sym2 V))))

/-- Pair-source projection identity with the extra event that the source hits `T`. -/
theorem setIntegral_sub_eq_projFunA_pair_conn (w : Sym2 V → unitInterval) (v w' a : V)
    (F : Set V → ℝ) (T : Finset V) :
    ∫ ω in pairAvoid v w' a ∩ pairConn v w' T,
        (F (pairCluster ω v w') - F (openCluster ω a)) ∂(prodBernoulli w) =
      ∫ ω in pairAvoid v w' a ∩ pairConn v w' T,
        projFunA w a F (pairCluster ω v w') ∂(prodBernoulli w) := by
  let 𝒮 : Set (Set (Sym2 V)) :=
    {K | ∃ t ∈ T, t = v ∨ t = w' ∨ ∃ e ∈ K, t ∈ e}
  have hcluster : {ω : BondConfig V |
      BHK2006.setCl ω ({v, w'} : Set V) ∈ 𝒮} = pairConn v w' T := by
    ext ω
    simp only [𝒮, pairConn, mem_setOf_eq]
    constructor
    · rintro ⟨t, ht, htv | htw | ⟨e, he, hte⟩⟩
      · subst t
        exact ⟨v, ht, Or.inl (SimpleGraph.Reachable.refl v)⟩
      · subst t
        exact ⟨w', ht, Or.inr (SimpleGraph.Reachable.refl w')⟩
      · obtain ⟨s, hs, he⟩ := (BHK2006.mem_setCl_iff ω ({v, w'} : Set V) e).1 he
        rcases hs with hs | hs
        · subst s
          exact ⟨t, ht, Or.inl ((reachable_iff_exists_mem_openEdgeCluster ω v t).2
            (Or.inr ⟨e, he, hte⟩))⟩
        · subst s
          exact ⟨t, ht, Or.inr ((reachable_iff_exists_mem_openEdgeCluster ω w' t).2
            (Or.inr ⟨e, he, hte⟩))⟩
    · rintro ⟨t, ht, hvt | hwt⟩
      · rcases (reachable_iff_exists_mem_openEdgeCluster ω v t).1 hvt with htv | ⟨e, he, hte⟩
        · exact ⟨t, ht, Or.inl htv⟩
        · exact ⟨t, ht, Or.inr (Or.inr ⟨e,
            (BHK2006.mem_setCl_iff ω ({v, w'} : Set V) e).2 ⟨v, Or.inl rfl, he⟩, hte⟩)⟩
      · rcases (reachable_iff_exists_mem_openEdgeCluster ω w' t).1 hwt with htw | ⟨e, he, hte⟩
        · exact ⟨t, ht, Or.inr (Or.inl htw)⟩
        · exact ⟨t, ht, Or.inr (Or.inr ⟨e,
            (BHK2006.mem_setCl_iff ω ({v, w'} : Set V) e).2 ⟨w', Or.inr rfl, he⟩, hte⟩)⟩
  rw [← hcluster]
  exact setIntegral_sub_eq_projFunA_pair_setCl w v w' a F 𝒮

/-- Given the explored edge cluster of `v`, the fresh-product probability that `w'` avoids `a`
after deleting all pairs meeting that cluster.  If `w'` belongs to the explored cluster, this
integral is automatically one on the conditioning event `v ↮ a`. -/
def pairAvoidCond (w : Sym2 V → unitInterval) (v w' a : V)
    (K : Set (Sym2 V)) : ℝ :=
  ∫ η, Percolation.Literature.DecisionTree.ind
      ((openConn a w')ᶜ : Set (BondConfig V))
      (η \ BHK2006.barOf ({v} : Set V) K) ∂(prodBernoulli w)

/-- The residual avoidance probability is nonnegative. -/
theorem pairAvoidCond_nonneg (w : Sym2 V → unitInterval) (v w' a : V)
    (K : Set (Sym2 V)) : 0 ≤ pairAvoidCond w v w' a K := by
  exact integral_nonneg fun η =>
    Percolation.Literature.DecisionTree.ind_nonneg
      ((openConn a w')ᶜ : Set (BondConfig V))
      (η \ BHK2006.barOf ({v} : Set V) K)

/-- Exploring a larger cluster deletes more pairs and therefore makes residual avoidance more
likely. -/
theorem monotone_pairAvoidCond (w : Sym2 V → unitInterval) (v w' a : V) :
    Monotone (pairAvoidCond w v w' a) := by
  intro K L hKL
  unfold pairAvoidCond
  refine integral_mono Integrable.of_finite Integrable.of_finite fun η => ?_
  have hsub : η \ BHK2006.barOf ({v} : Set V) L ⊆
      η \ BHK2006.barOf ({v} : Set V) K :=
    Set.sdiff_subset_sdiff_right (BHK2006.barOf_mono ({v} : Set V) hKL)
  by_cases hη : η \ BHK2006.barOf ({v} : Set V) K ∈
      ((openConn a w')ᶜ : Set (BondConfig V))
  · have hη' : η \ BHK2006.barOf ({v} : Set V) L ∈
        ((openConn a w')ᶜ : Set (BondConfig V)) := by
      intro hconn
      exact hη (hconn.mono (openGraph_mono hsub))
    rw [Percolation.Literature.DecisionTree.ind_of_mem hη,
      Percolation.Literature.DecisionTree.ind_of_mem hη']
  · rw [Percolation.Literature.DecisionTree.ind_of_not_mem hη]
    exact Percolation.Literature.DecisionTree.ind_nonneg _ _

/-- Tower identity for the second avoidance event after exploring `C_v`: integrating any
function of the explored edge cluster over `{v,w'} ↮ a` is the same as multiplying it, on
`{v ↮ a}`, by the residual avoidance probability. -/
theorem tower_pairAvoidCond (w : Sym2 V → unitInterval) (v w' a : V)
    (g : Set (Sym2 V) → ℝ) :
    ∫ ω in pairAvoid v w' a, g (openEdgeCluster ω v) ∂(prodBernoulli w) =
      ∫ ω in {ω : BondConfig V | ¬ (openGraph ω).Reachable v a},
        g (openEdgeCluster ω v) *
          pairAvoidCond w v w' a (openEdgeCluster ω v) ∂(prodBernoulli w) := by
  classical
  set D : Set (BondConfig V) :=
    {ω : BondConfig V | ¬ (openGraph ω).Reachable v a} with hD
  set Q : Set (BondConfig V) := (openConn a w')ᶜ with hQ
  have hpair : pairAvoid v w' a = D ∩ Q := by
    ext ω
    simp only [pairAvoid, hD, hQ, mem_setOf_eq, mem_inter_iff, mem_compl_iff, openConn]
    constructor
    · rintro ⟨hv, hw⟩
      exact ⟨hv, fun h => hw h.symm⟩
    · rintro ⟨hv, hw⟩
      exact ⟨hv, fun h => hw h.symm⟩
  let N : Set (Sym2 V) → ℝ := fun L =>
    if w' = a ∨ ∃ e ∈ L, w' ∈ e then 0 else 1
  have hN : ∀ ξ : BondConfig V,
      N (openEdgeCluster ξ a) =
        Percolation.Literature.DecisionTree.ind Q ξ := by
    intro ξ
    have hr := reachable_iff_exists_mem_openEdgeCluster ξ a w'
    by_cases h : (openGraph ξ).Reachable a w'
    · simp only [N, if_pos (hr.1 h)]
      rw [
        Percolation.Literature.DecisionTree.ind_of_not_mem]
      intro hξ
      exact hξ h
    · simp only [N, if_neg (fun hp => h (hr.2 hp))]
      rw [
        Percolation.Literature.DecisionTree.ind_of_mem]
      exact h
  have hDiff : ∀ ω : BondConfig V, ω ∈ D ↔
      ∀ s ∈ ({v} : Set V), ∀ t ∈ ({a} : Set V),
        ¬ (openGraph ω).Reachable s t := by
    intro ω
    simp only [hD, mem_setOf_eq, mem_singleton_iff, forall_eq]
  have hm : ∑ ω : Set (Sym2 V), BHK2006.weight (fun e => (w e : ℝ)) ω = 1 := by
    have h1 := BHK2006.integral_prodBernoulli_eq_sum w fun _ => (1 : ℝ)
    simp only [integral_const, probReal_univ, smul_eq_mul, mul_one] at h1
    exact h1.symm
  have key := BHK2006.set_sum_cond_cluster (fun e => (w e : ℝ)) hm
    ({v} : Set V) ({a} : Set V) (fun K L => g K * N L) hDiff
  simp only [BHK2006.setCl_singleton] at key
  have halpha : ∀ K : Set (Sym2 V), pairAvoidCond w v w' a K =
      ∑ η : Set (Sym2 V), BHK2006.weight (fun e => (w e : ℝ)) η *
        N (openEdgeCluster
          (η \ BHK2006.barOf ({v} : Set V) K) a) := by
    intro K
    rw [pairAvoidCond, BHK2006.integral_prodBernoulli_eq_sum]
    refine Finset.sum_congr rfl fun η _ => ?_
    rw [hN]
  have hinner : ∀ K : Set (Sym2 V),
      (∑ η : Set (Sym2 V), BHK2006.weight (fun e => (w e : ℝ)) η *
        (g K * N (openEdgeCluster
          (η \ BHK2006.barOf ({v} : Set V) K) a))) =
        g K * pairAvoidCond w v w' a K := by
    intro K
    rw [halpha, Finset.mul_sum]
    refine Finset.sum_congr rfl fun η _ => ?_
    ring
  rw [hpair, Percolation.Literature.LonePortSum.setIntegral_eq_sum,
    Percolation.Literature.LonePortSum.setIntegral_eq_sum]
  calc
    ∑ ω, BHK2006.weight (fun e => (w e : ℝ)) ω *
        (g (openEdgeCluster ω v) *
          Percolation.Literature.DecisionTree.ind (D ∩ Q) ω) =
      ∑ ω, BHK2006.weight (fun e => (w e : ℝ)) ω *
        ((g (openEdgeCluster ω v) * N (openEdgeCluster ω a)) *
          Percolation.Literature.DecisionTree.ind D ω) := by
        refine Finset.sum_congr rfl fun ω _ => ?_
        rw [BHK2006.ind_inter, hN]
        ring
    _ = ∑ ω, BHK2006.weight (fun e => (w e : ℝ)) ω *
        ((∑ η, BHK2006.weight (fun e => (w e : ℝ)) η *
          (g (openEdgeCluster ω v) *
            N (openEdgeCluster
              (η \ BHK2006.barOf ({v} : Set V) (openEdgeCluster ω v)) a))) *
          Percolation.Literature.DecisionTree.ind D ω) := key
    _ = ∑ ω, BHK2006.weight (fun e => (w e : ℝ)) ω *
        ((g (openEdgeCluster ω v) *
          pairAvoidCond w v w' a (openEdgeCluster ω v)) *
          Percolation.Literature.DecisionTree.ind D ω) := by
        refine Finset.sum_congr rfl fun ω _ => ?_
        rw [hinner]

/-- **Overlap lemma.**  If `a` has no larger cluster-functional mean than the source vertex `v`,
then the pair-source cluster dominates `C_a` on the event that the pair avoids `a`. -/
theorem overlap_pair (w : Sym2 V → unitInterval) (v w' a : V) (F : Set V → ℝ)
    (hF : ∀ S T : Set V, S ⊆ T → F S ≤ F T)
    (hmin : (∫ ω, F (openCluster ω a) ∂(prodBernoulli w)) ≤
      ∫ ω, F (openCluster ω v) ∂(prodBernoulli w)) :
    0 ≤ ∫ ω in pairAvoid v w' a,
      (F (pairCluster ω v w') - F (openCluster ω a)) ∂(prodBernoulli w) := by
  classical
  by_cases hav : a = v
  · subst a
    have hempty : pairAvoid v w' v = (∅ : Set (BondConfig V)) := by
      ext ω
      simp [pairAvoid]
    rw [hempty]
    simp
  set μ := prodBernoulli w with hμ
  set D : Set (BondConfig V) :=
    {ω : BondConfig V | ¬ (openGraph ω).Reachable v a} with hD
  let p : Set (Sym2 V) → ℝ := fun K =>
    projFunA w a F {x | x = v ∨ ∃ e ∈ K, x ∈ e}
  have hpmono : Monotone p := by
    exact KNPreFKG.monotone_clusterFun v (projFunA w a F)
      (monotone_projFunA w a F hF)
  have hDset : {ω : BondConfig V |
      ∀ x ∈ ({a} : Set V), ¬ (openGraph ω).Reachable v x} = D := by
    ext ω
    simp [hD]
  have hBHK := BHK2006_clusterConditionalPositiveAssociation_holds V w v
    ({a} : Set V) p (pairAvoidCond w v w' a) hpmono
    (monotone_pairAvoidCond w v w' a) (by simpa using Ne.symm hav)
  rw [hDset] at hBHK
  have htower := tower_pairAvoidCond w v w' a p
  rw [← hD] at htower
  rw [← htower] at hBHK
  have hpint : 0 ≤ ∫ ω in D, p (openEdgeCluster ω v) ∂μ := by
    have hproj := setIntegral_projFunA_avoid w a v F
    rw [hDset] at hproj
    have hpcluster : ∀ ω : BondConfig V,
        p (openEdgeCluster ω v) = projFunA w a F (openCluster ω v) := by
      intro ω
      exact KNPreFKG.clusterFun_openEdgeCluster (projFunA w a F) ω v
    have heq : (∫ ω in D, p (openEdgeCluster ω v) ∂μ) =
        ∫ ω in D, projFunA w a F (openCluster ω v) ∂μ :=
      setIntegral_congr_fun (MeasurableSet.of_discrete) fun ω _ => hpcluster ω
    rw [heq, hproj]
    exact sub_nonneg.2 hmin
  have halpha : 0 ≤ ∫ ω in D,
      pairAvoidCond w v w' a (openEdgeCluster ω v) ∂μ :=
    setIntegral_nonneg (MeasurableSet.of_discrete) fun ω _ =>
      pairAvoidCond_nonneg w v w' a (openEdgeCluster ω v)
  have hpairp : 0 ≤ ∫ ω in pairAvoid v w' a,
      p (openEdgeCluster ω v) ∂μ := by
    by_cases hD0 : μ.real D = 0
    · have hsub : pairAvoid v w' a ⊆ D := by
        intro ω hω
        exact hω.1
      have hreal0 : μ.real (pairAvoid v w' a) = 0 :=
        le_antisymm ((measureReal_mono hsub).trans hD0.le) measureReal_nonneg
      have hnull : μ (pairAvoid v w' a) = 0 :=
        (measureReal_eq_zero_iff (measure_ne_top _ _)).1 hreal0
      rw [setIntegral_measure_zero _ hnull]
    · have hDpos : 0 < μ.real D :=
        lt_of_le_of_ne measureReal_nonneg (Ne.symm hD0)
      have hleft : 0 ≤
          (∫ ω in D, p (openEdgeCluster ω v) ∂μ) *
            ∫ ω in D, pairAvoidCond w v w' a (openEdgeCluster ω v) ∂μ :=
        mul_nonneg hpint halpha
      have hprod : 0 ≤ μ.real D *
          ∫ ω in pairAvoid v w' a, p (openEdgeCluster ω v) ∂μ :=
        le_trans hleft hBHK
      by_contra hneg
      have := mul_neg_of_pos_of_neg hDpos (lt_of_not_ge hneg)
      linarith
  have hmonoInt :
      (∫ ω in pairAvoid v w' a,
        projFunA w a F (openCluster ω v) ∂μ) ≤
      ∫ ω in pairAvoid v w' a,
        projFunA w a F (pairCluster ω v w') ∂μ := by
    refine setIntegral_mono_on (Integrable.of_finite).integrableOn
      (Integrable.of_finite).integrableOn (MeasurableSet.of_discrete) fun ω _ => ?_
    exact monotone_projFunA w a F hF (subset_union_left)
  have hpcluster : ∀ ω : BondConfig V,
      p (openEdgeCluster ω v) = projFunA w a F (openCluster ω v) := by
    intro ω
    exact KNPreFKG.clusterFun_openEdgeCluster (projFunA w a F) ω v
  simp only [hpcluster] at hpairp
  rw [setIntegral_sub_eq_projFunA_pair w v w' a F]
  exact hpairp.trans hmonoInt

end KNAll

end
