import Hypergraph.CoreFrontier

/-!
# Local damage generated by one-owner core probes

A rejected core batch closes its examined centre automatically through
`BDDom.Transcript.step`.  Its separate collateral-damage set therefore contains only the new
frontier heads whose probes were touched.  Every such head is a nearest neighbour of the centre,
is not already open, and there are at most four of them.
-/

noncomputable section

namespace KNAll.Site.CoreDamage

open Set Percolation.Literature Percolation.Literature.LatticeModels
open KNAll.Site

variable {d : Nat} [NeZero d]

/-- The maximal collateral set of a core batch.  The centre itself is omitted because the
bounded-damage step closes it separately on failure. -/
def damage (h : MacroExp.Tr d) (z : Site 2) : Finset (Site 2) :=
  CoreFrontier.newHeads (d := d) h z

omit [NeZero d] in
@[simp] theorem mem_damage {h : MacroExp.Tr d} {z y : Site 2} :
    y ∈ damage h z ↔ y ∈ CoreFrontier.newHeads (d := d) h z := Iff.rfl

/-- Every possible collateral closure is adjacent to the failed centre. -/
theorem damage_local (h : MacroExp.Tr d) (z : Site 2) :
    ∀ y ∈ damage h z, (zdGraph 2).Adj z y := by
  intro y hy
  exact MacroExp.adj_of_mem_nbrs
    ((MacroExp.mem_pending (d := d)).1
      ((CoreFrontier.mem_newHeads (d := d)).1 hy).1).1

/-- New heads are disjoint from the already open macro vertices. -/
theorem damage_disjoint_open (h : MacroExp.Tr d) (z : Site 2) :
    Disjoint (damage h z) h.openV := by
  rw [Finset.disjoint_left]
  intro y hy hyo
  exact CoreFrontier.newHead_not_mem_openV (d := d) hy hyo

/-- At most four collateral vertices can be closed by one failed core batch. -/
theorem card_damage_le_four (h : MacroExp.Tr d) (z : Site 2) :
    (damage h z).card ≤ 4 :=
  CoreFrontier.card_newHeads_le_four (d := d) h z

/-- Any actually touched subset inherits the nearest-neighbour property. -/
theorem touched_local {h : MacroExp.Tr d} {z : Site 2} {touched : Finset (Site 2)}
    (ht : touched ⊆ damage h z) :
    ∀ y ∈ touched, z = y ∨ (zdGraph 2).Adj z y := by
  intro y hy
  exact Or.inr (damage_local h z y (ht hy))

/-- Any actually touched subset remains disjoint from the open macro vertices. -/
theorem touched_disjoint_open {h : MacroExp.Tr d} {z : Site 2}
    {touched : Finset (Site 2)} (ht : touched ⊆ damage h z) :
    Disjoint touched h.openV :=
  (damage_disjoint_open h z).mono_left ht

/-- Any actually touched subset has at most four vertices. -/
theorem card_touched_le_four {h : MacroExp.Tr d} {z : Site 2}
    {touched : Finset (Site 2)} (ht : touched ⊆ damage h z) :
    touched.card ≤ 4 :=
  (Finset.card_le_card ht).trans (card_damage_le_four h z)

/-- Including the failed centre gives a closed batch of size at most five. -/
theorem card_insert_touched_le_five {h : MacroExp.Tr d} {z : Site 2}
    {touched : Finset (Site 2)} (ht : touched ⊆ damage h z) :
    (insert z touched).card ≤ 5 := by
  calc
    (insert z touched).card ≤ touched.card + 1 := Finset.card_insert_le z touched
    _ ≤ 5 := by
      have h4 := card_touched_le_four ht
      omega

#print axioms KNAll.Site.CoreDamage.damage_local
#print axioms KNAll.Site.CoreDamage.damage_disjoint_open
#print axioms KNAll.Site.CoreDamage.card_damage_le_four
#print axioms KNAll.Site.CoreDamage.touched_local
#print axioms KNAll.Site.CoreDamage.touched_disjoint_open
#print axioms KNAll.Site.CoreDamage.card_touched_le_four
#print axioms KNAll.Site.CoreDamage.card_insert_touched_le_five

end KNAll.Site.CoreDamage

end
